name: Bug Report
description: Report a problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        *Before reporting, search our [existing issues](https://github.com/ritamsarmah/accelerate/issues?q=label%3Abug) to see if the bug has already been addressed.*
  - type: textarea
    id: desc
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: "Steps to Reproduce"
      description: "Step-by-step instructions to reproduce this bug."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: "Accelerate Version"
      placeholder: "e.g., 4.0.3"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system(s) is this bug occurring on?
      multiple: true
      options:
        - macOS
        - iOS
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Additional Info"
      description: |
        Include any further context, such as OS version, screenshots, or video recordings.
      placeholder: "Tip: Attach files by clicking this area and dragging files in"
    validations:
      required: false

